### ISSUE TITLE
package-lock.json is at it again

### ISSUE THREAD

**Issue by eric-foy** [RLey/wsu-tunnel-app#34]
formating in package-lock.json under root of project is off.

probably best to delete it and recreate with npm install. someone may want to commit the new one.

**Comment by tux2603** [comment]
Looking at the file, I think that it would be better just to add it to the .gitignore file. Since we don't have the node modules in the repo, it doesn't really make sense to have a file that keeps track of what version of the modules is being used.

**Comment by tux2603** [comment]
I checked the .gitignore file and it lists package-lock.json as one of the files to be ignored.  Since the file never makes it to the repository, you can do whatever you feel necessary to fix it on your machine.

**Comment by eric-foy** [comment]
Sounds good to me, npm states that one should commit the file but after reading:
https://stackoverflow.com/questions/46164194/what-is-the-point-of-putting-npms-package-lock-json-under-version-control
I think we should ignore it.
