### ISSUE TITLE
nothing to do

### ISSUE THREAD

**Issue by eric-foy** [RLey/wsu-tunnel-app#66]
can't find much to do with the server, should I work any any open issues that no one is assigned (not sure if there are any). I think other people may be in the same boat so I suggest maybe we spam issues and not assign anyone and then people can pick them up when they are ready to do work.

**Comment by rjslater2000** [comment]
Matt and I still have to discuss some things for the database but I'm not sure we'll have much to do either. Let's move the database to AWS then I think we should get it released to the public so we can start getting bug reports
