### ISSUE TITLE
Crash on help page

### ISSUE THREAD

**Issue by rjslater2000** [RLey/wsu-tunnel-app#74]
On Chrome mobile, hit help, then rotate the screen and rotate it back. Repeat the rotation a few times. Seems like we're trying to rotate the map but it doesn't exist so it crashes

**Comment by rjslater2000** [comment]
![Screenshot_20190411-133000](https://user-images.githubusercontent.com/20517031/55978716-75876700-5c5e-11e9-9519-048dcbe04b3a.jpg)

**Comment by eric-foy** [comment]
Changed the help page, can you see if still crashing. New url is http://localhost:3000/ only and help is in an html div tag.

**Comment by tux2603** [comment]
The issue is fixed on my phone, which I believe is android lollipop.
